#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3><b>ENGAGE ALL 5 EXPERIENCES</h3></b>
  
  <b>ENVISION: 3D MESSAGE</b> See Below <br>
  
  <b>EXPLORE: 4D AUGMENTED REALITY</b> AR On Mobile Only <br>
  
  <a href="https://avertek.net/xr-now-health-care"><b>EDUCATE:</b> See More</a> 
  
  <a href="https://avertek.net/narrative"><b>ENLIGHTEN:</b> Review Testimonials</a>
  
  <a href="https://avertek.net/contact-us"><b>DISCOVER:</b> Learn More & Receive Free Gift</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
